import { ModeContextProvider } from "@-ft/mode-next";
import type { Metadata } from "next";
import { ThisIsClientComponent } from "./components/ThisIsClientComponent";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="/mode.js" />
      </head>
      <body>
        <ThisIsClientComponent>
          <ModeContextProvider variableName="npm:@-ft/mode-codegen">
            {children}
          </ModeContextProvider>
        </ThisIsClientComponent>
      </body>
    </html>
  );
}
